# File Ingestion

CHUNK_SIZE = 3000
CHUNK_OVERLAP = 300

# OpenAI

EMBEDDING_MODEL = "text-embedding-3-small"
GENERATION_MODEL = "gpt-4o-mini"

# ChromaDB

CHROMADB_PATH = "./database/"
COLLECTION_NAME = "dnd"

# Sources

SOURCE_DIR = "./sources/"